development:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: fedena
      password: fedenapassword

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: fedena
      password: fedenapassword

production:
      host: localhost
      adapter: mysql
      database: fedena_ultimate
      port: 3306
      username: fedena
      password: fedenapassword
cucumber:
  <<: *test
