#development:
#  adapter: postgresql
#  host: localhost
#  username: user
#  database: app-dev

development:
      host: localhost
      adapter: postgresql
      database: fedena_ultimate
#      port: 3306
      username: postgres
      password: postgres

test: &test
      host: localhost
      adapter: mysql
      database: fedena_two_new
      port: 3306
      username: fedena
      password: fedenapassword

production:
      host: localhost
      adapter: postgresql
      database: fedena_ultimate
      port: 3306
      username: postgres
      password: postgres
cucumber:
  <<: *test
